### ISSUE TITLE
Not return properly formed csproj

### ISSUE THREAD

**Issue by dnbr2002** [loresoft/DotNet.Property#1]
I was super excited to find this tool.  I need to update csproj properties in a jenkins pipeline and it seems to work great for update Version, etc.   But upon further inspection i noticed a bug I believe.  

Details

**Expected** 

I have this csproj

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <ProjectGuid>{9A19103F-16F7-4668-BE54-9A1E7A4F7556}</ProjectGuid>
    <PackageId>JLT.dotnet-api-214-openshift</PackageId>
    <Description>.Net Core 2.1.5 Sample WebApi</Description>
    <RepositoryUrl>https://whatever/stash</RepositoryUrl>
    <Version>1.0.0</Version>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.4" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.1.1" />
    <PackageReference Include="microsoft.aspnetcore.http.abstractions" Version="2.1.1" />
    <PackageReference Include="microsoft.aspnetcore.mvc" Version="2.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
  </ItemGroup>
</Project>
```

I run 
`dotnet property '**/dotnet-api-214-openshift.csproj' Version:1.0.22`

I should get an updated cspproj with the new version like the one below

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <ProjectGuid>{9A19103F-16F7-4668-BE54-9A1E7A4F7556}</ProjectGuid>
    <PackageId>JLT.dotnet-api-214-openshift</PackageId>
    <Description>.Net Core 2.1.5 Sample WebApi</Description>
    <RepositoryUrl>https://whatever/stash</RepositoryUrl>
    <Version>1.0.22</Version>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.4" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.1.1" />
    <PackageReference Include="microsoft.aspnetcore.http.abstractions" Version="2.1.1" />
    <PackageReference Include="microsoft.aspnetcore.mvc" Version="2.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
  </ItemGroup>
</Project>
```

**Actual Result** 

Instead I get this csproj below which has the version updated but if you look the end of the file there are some extra characters which makes the xml not properly formed anymore.  

**_</Project>t>_**

```
﻿<Project Sdk="Microsoft.NET.Sdk.Web">
   <PropertyGroup>
     <TargetFramework>netcoreapp2.1</TargetFramework>
     <ProjectGuid>{9A19103F-16F7-4668-BE54-9A1E7A4F7556}</ProjectGuid>
     <PackageId>JLT.dotnet-api-214-openshift</PackageId>
     <Description>.Net Core 2.1.5 Sample WebApi</Description>
     <RepositoryUrl>https://stash.ba.ssa.gov/scm/jlt/dotnet-api-214-openshift</RepositoryUrl>
     <Version>1.0.22</Version>
     <IsPackable>false</IsPackable>
   </PropertyGroup>
   <ItemGroup>
     <Folder Include="wwwroot\" />
   </ItemGroup>
   <ItemGroup>
     <PackageReference Include="Microsoft.AspNetCore" Version="2.1.4" />
     <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.1.1" />
     <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.1.1" />
     <PackageReference Include="microsoft.aspnetcore.http.abstractions" Version="2.1.1" />
     <PackageReference Include="microsoft.aspnetcore.mvc" Version="2.1.3" />
     <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
   </ItemGroup>
 </Project>t>
```

This is a great tool and I see a lot of use for it since MS doesn't provide this natively.  I hope this is something small or I'm just missing something because I really need some sort of version tooling in the jenkins pipeline that I can start using.  Otherwise I have to put a hacky bit together to do what this is doing.

**Comment by akshaybheda** [comment]
Hi, I tried creating a test case for your scenario, I was not able to get any error and works as expected.

**Comment by dnbr2002** [comment]
I think it has to do when you go from UTF-8 to UTF-8 BOM (your tool defaults to UTF-8 BOM).  My csproj is UTF-8.  Then i change the version and it bumps out the characters somehow.  

I tried another tool, This one https://github.com/TAGC/dotnet-setversion returns UTF-8, my original encode type. I have no variances so I am using it now.  

But with your tool I had 

UTF8 - dotnet-api-214-openshift.csproj - with Version 1.0.0
I run 

`dotnet property '**/dotnet-api-214-openshift.csproj' Version:1.0.22`

I get UTF-8 with BOM  dotnet-api-214-openshift.cspro but with the messed up 't>' at the end.  

Maybe try messing with that to recreate.

**Comment by dnbr2002** [comment]
to make it mess up.  you have play with the version depths after you go from UTF-8 to UTF-8 BOM

So do 

UTF8 - dotnet-api-214-openshift.csproj - with Version 1.0.0
I run
`dotnet property '**/dotnet-api-214-openshift.csproj' Version:1.0.22.22`

then run 
`dotnet property '**/dotnet-api-214-openshift.csproj' Version:1.0.2`

this should change version to 1.0.2

but your last line in csproj will be
</Project>**ect>**

That is most producible and predictable example I can give in windows bash.
